---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      excludes:
        - .git
        - .vagrant
        - .molecule
        - venv
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
